"""Inject non-clinical SOURCE-build provenance into the Pages deployment artifact.

This script is owned by the bounded Pages build-provenance worker. It must:

* Emit ONLY source-build provenance: commit SHA, UTC build timestamp, the
  source repository, and a GitHub Actions run URL. It must NOT infer or
  publish any clinical, gating, or test-result evidence.
* Refuse to inject anything if any field is malformed so the helper either
  emits a complete, schema-valid payload or fails the deploy job loudly.
* Serialize via ``json.dumps`` (no ``innerHTML``-style concatenation) and
  rely on the helper reading ``window.__BUILD_META__`` via ``textContent``
  to avoid HTML or script injection.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import re
from pathlib import Path


SENTINEL = "/* __BUILD_META__ generated by CI; do not edit. */"
SOURCE = "ci"
SHA_PATTERN = re.compile(r"\A[0-9a-f]{40}\Z")
REPO_PATTERN = re.compile(r"\A[A-Za-z0-9._-]+/[A-Za-z0-9._-]+\Z")
RUN_ID_PATTERN = re.compile(r"\A[1-9][0-9]{0,18}\Z")
BUILT_AT_PATTERN = re.compile(r"\A\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\Z")


class MetadataError(ValueError):
    """Raised when build metadata inputs fail validation."""


def _validate_commit(commit: str) -> str:
    if not isinstance(commit, str):
        raise MetadataError("commit must be a string")
    cleaned = commit.strip()
    if not SHA_PATTERN.match(cleaned):
        raise MetadataError(
            f"commit must be a 40-character lowercase hex SHA; got {commit!r}"
        )
    return cleaned


def _validate_repository(repository: str) -> str:
    if not isinstance(repository, str):
        raise MetadataError("repository must be a string")
    cleaned = repository.strip()
    if not REPO_PATTERN.match(cleaned):
        raise MetadataError(
            "repository must be in 'owner/name' form (ASCII letters, digits, '.', '_', '-'); "
            f"got {repository!r}"
        )
    owner, name = cleaned.split("/", 1)
    if owner[0] in ".-_" or name[0] in ".-_":
        raise MetadataError(
            "repository owner and name must start with an alphanumeric character; "
            f"got {repository!r}"
        )
    return cleaned


def _validate_run_id(run_id: str) -> str:
    if not isinstance(run_id, str):
        raise MetadataError("run_id must be a string")
    cleaned = run_id.strip()
    if not RUN_ID_PATTERN.match(cleaned):
        raise MetadataError(
            f"run_id must be a positive integer in plain decimal; got {run_id!r}"
        )
    return cleaned


def _validate_built_at(built_at: str) -> str:
    if not isinstance(built_at, str):
        raise MetadataError("built_at must be a string")
    cleaned = built_at.strip()
    if not BUILT_AT_PATTERN.match(cleaned):
        raise MetadataError(
            "built_at must be an RFC3339 UTC timestamp ending in 'Z' "
            f"(YYYY-MM-DDTHH:MM:SSZ); got {built_at!r}"
        )
    parsed = datetime.strptime(cleaned, "%Y-%m-%dT%H:%M:%SZ").replace(
        tzinfo=timezone.utc
    )
    if parsed.utcoffset() != timezone.utc.utcoffset(parsed):
        raise MetadataError("built_at must represent a UTC instant")
    return cleaned


def _short_commit(commit: str) -> str:
    return commit[:7]


def build_run_url(repository: str, run_id: str) -> str:
    return f"https://github.com/{repository}/actions/runs/{run_id}"


def build_metadata(
    *,
    commit: str,
    built_at: str,
    repository: str,
    run_id: str,
) -> dict[str, object]:
    """Validate inputs and assemble the SOURCE-build provenance payload.

    The returned dictionary contains only source-build provenance fields. It
    is deliberately free of any clinical, gating, or test-result evidence.
    """

    clean_commit = _validate_commit(commit)
    clean_repo = _validate_repository(repository)
    clean_run_id = _validate_run_id(run_id)
    clean_built_at = _validate_built_at(built_at)
    return {
        "commit": clean_commit,
        "short_commit": _short_commit(clean_commit),
        "built_at": clean_built_at,
        "repository": clean_repo,
        "run_id": clean_run_id,
        "run_url": build_run_url(clean_repo, clean_run_id),
        "source": SOURCE,
    }


def render_metadata_script(metadata: dict[str, object]) -> str:
    """Serialize metadata using ``json.dumps`` for safe HTML embedding.

    ``json.dumps`` escapes the forward slash so an injected ``</script>``
    payload cannot terminate the surrounding script tag.
    """

    payload = json.dumps(metadata, sort_keys=True, ensure_ascii=True)
    # Belt-and-braces check: refuse to render if any literal would break out.
    if "</script" in payload.lower():
        raise MetadataError("metadata payload would break the script tag")
    return f"<script>{SENTINEL}window.__BUILD_META__ = {payload};</script>"


def inject_metadata(*, html_path: Path, metadata: dict[str, object]) -> None:
    html = html_path.read_text(encoding="utf-8")
    if SENTINEL in html:
        raise MetadataError("build metadata was already injected")
    if "</head>" not in html:
        raise MetadataError("Pages document has no closing head tag")
    script = render_metadata_script(metadata)
    html_path.write_text(
        html.replace("</head>", f"{script}\n  </head>", 1),
        encoding="utf-8",
    )


def resolve_built_at(explicit: str | None) -> str:
    if explicit:
        return explicit
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parents[1]
    )
    parser.add_argument("--commit", required=True)
    parser.add_argument("--built-at")
    parser.add_argument("--repository", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--html", type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    metadata = build_metadata(
        commit=args.commit,
        built_at=resolve_built_at(args.built_at),
        repository=args.repository,
        run_id=args.run_id,
    )
    target = (args.html or (root / "docs" / "index.html")).resolve()
    inject_metadata(html_path=target, metadata=metadata)
    print(json.dumps(metadata, sort_keys=True, ensure_ascii=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
